#!/bin/bash
# git autocomplete
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

#gnu coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

#homebrew
export PATH=/usr/local/bin:$PATH

#macports
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

#npm
export PATH=/usr/local/share/npm/bin/:$PATH

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

#go
export GOROOT=~/Documents/go/
